-- MySQL Script generated by MySQL Workbench
-- Sun Apr 28 23:18:18 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema EducaPlus
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema EducaPlus
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `EducaPlus` DEFAULT CHARACTER SET utf8 ;
USE `EducaPlus` ;

-- -----------------------------------------------------
-- Table `EducaPlus`.`materias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `EducaPlus`.`materias` (
  `id_materias` BIGINT NOT NULL,
  `materia_nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_materias`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `EducaPlus`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `EducaPlus`.`users` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `senha` VARCHAR(355) NOT NULL,
  `nivel` VARCHAR(45) NOT NULL,
  `materia_id` BIGINT NULL,
  PRIMARY KEY (`id`),
  INDEX `materia_id_idx` (`materia_id` ASC) VISIBLE,
  CONSTRAINT `materia_id`
    FOREIGN KEY (`materia_id`)
    REFERENCES `EducaPlus`.`materias` (`id_materias`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `EducaPlus`.`atividades`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `EducaPlus`.`atividades` (
  `id_atividade` VARCHAR(355) NOT NULL,
  `materia_id` BIGINT NOT NULL,
  `titulo` VARCHAR(45) NOT NULL,
  `tipo` VARCHAR(45) NOT NULL,
  `descricao` VARCHAR(100) NOT NULL,
  `questoes` VARCHAR(200) NOT NULL,
  `resposta_aluno` VARCHAR(100) NULL,
  `professor_id` BIGINT NOT NULL,
  `resposta_certa` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id_atividade`),
  INDEX `materia_id_idx` (`materia_id` ASC) VISIBLE,
  INDEX `professor_id_idx` (`professor_id` ASC) VISIBLE,
  CONSTRAINT `materia_id`
    FOREIGN KEY (`materia_id`)
    REFERENCES `EducaPlus`.`materias` (`id_materias`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `professor_id`
    FOREIGN KEY (`professor_id`)
    REFERENCES `EducaPlus`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `EducaPlus`.`conteudo_extra`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `EducaPlus`.`conteudo_extra` (
  `id_conteudo_extra` VARCHAR(355) NOT NULL,
  `materia_id` BIGINT NOT NULL,
  `titulo` VARCHAR(45) NOT NULL,
  `tipo` VARCHAR(45) NOT NULL,
  `descricao` VARCHAR(200) NULL,
  `video_url` VARCHAR(355) NULL,
  `professor_id` BIGINT NOT NULL,
  PRIMARY KEY (`id_conteudo_extra`),
  INDEX `materia_id_idx` (`materia_id` ASC) VISIBLE,
  INDEX `professor_id_idx` (`professor_id` ASC) VISIBLE,
  CONSTRAINT `materia_id`
    FOREIGN KEY (`materia_id`)
    REFERENCES `EducaPlus`.`materias` (`id_materias`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `professor_id`
    FOREIGN KEY (`professor_id`)
    REFERENCES `EducaPlus`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `EducaPlus`.`feedbacks_atividades`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `EducaPlus`.`feedbacks_atividades` (
  `id_feedback` VARCHAR(355) NOT NULL,
  `atividade_id` VARCHAR(355) NOT NULL,
  `opiniao` VARCHAR(300) NOT NULL,
  `experiencia` VARCHAR(45) NOT NULL,
  `usuario_id` BIGINT NOT NULL,
  PRIMARY KEY (`id_feedback`),
  INDEX `atividade_id_idx` (`atividade_id` ASC) VISIBLE,
  INDEX `usuario_id_idx` (`usuario_id` ASC) VISIBLE,
  CONSTRAINT `atividade_id`
    FOREIGN KEY (`atividade_id`)
    REFERENCES `EducaPlus`.`atividades` (`id_atividade`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `usuario_id`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `EducaPlus`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `EducaPlus`.`atividades_feitas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `EducaPlus`.`atividades_feitas` (
  `id_atividade_feita` VARCHAR(355) NOT NULL,
  `atividade_id` VARCHAR(355) NOT NULL,
  `resposta` VARCHAR(200) NULL,
  `alunos_id` BIGINT NOT NULL,
  PRIMARY KEY (`id_atividade_feita`),
  INDEX `atividade_id_idx` (`atividade_id` ASC) VISIBLE,
  INDEX `alunos_id_idx` (`alunos_id` ASC) VISIBLE,
  CONSTRAINT `atividade_id`
    FOREIGN KEY (`atividade_id`)
    REFERENCES `EducaPlus`.`atividades` (`id_atividade`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `alunos_id`
    FOREIGN KEY (`alunos_id`)
    REFERENCES `EducaPlus`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `EducaPlus`.`atividade_feita_notas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `EducaPlus`.`atividade_feita_notas` (
  `id_atividade_feita_notas` INT NOT NULL,
  `atividade_feita_id` VARCHAR(355) NOT NULL,
  `nota` DOUBLE NULL,
  `avaliador` BIGINT NOT NULL,
  PRIMARY KEY (`id_atividade_feita_notas`),
  INDEX `atividade_feita_id_idx` (`atividade_feita_id` ASC) VISIBLE,
  INDEX `avaliador` (`avaliador` ASC) VISIBLE,
  CONSTRAINT `atividade_feita_id`
    FOREIGN KEY (`atividade_feita_id`)
    REFERENCES `EducaPlus`.`atividades_feitas` (`id_atividade_feita`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `avaliador`
    FOREIGN KEY (`avaliador`)
    REFERENCES `EducaPlus`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `EducaPlus`.`user_analise`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `EducaPlus`.`user_analise` (
  `id` BIGINT NOT NULL,
  `login` VARCHAR(45) NOT NULL,
  `senha` VARCHAR(355) NOT NULL,
  `motivo` VARCHAR(200) NOT NULL,
  `tipo_usuario` VARCHAR(45) NOT NULL,
  `materia_user_analise` BIGINT NULL,
  PRIMARY KEY (`id`),
  INDEX `materia_user_analise_idx` (`materia_user_analise` ASC) INVISIBLE,
  CONSTRAINT `materia_user_analise`
    FOREIGN KEY (`materia_user_analise`)
    REFERENCES `EducaPlus`.`materias` (`id_materias`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
